# Generated by Django 2.1.1 on 2018-10-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):
    atomic = False # <<<< THIS LINE
    dependencies = [
        ('clientes', '0005_auto_20181001_0655'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Empregado',
        ),
        migrations.RenameField(
            model_name='telefone',
            old_name='client',
            new_name='empregado',
        ),
    ]
