# Generated by Django 2.1.1 on 2018-10-01 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_auto_20181001_2116'),
    ]

    operations = [
        migrations.AddField(
            model_name='empregado',
            name='departamentos',
            field=models.ManyToManyField(blank=True, null=True, to='clientes.Departamento'),
        ),
    ]
